<?php

namespace Database\Seeders;

use App\Models\NavigationMenu;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Schema;

class NavigationMenuSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        NavigationMenu::query()->delete();
        Schema::enableForeignKeyConstraints();

        $now = now();
        $menus = [
            [
                'id' => 1,
                'parent_id' => null,
                'label' => 'Dashboard',
                'label_en' => 'Dashboard',
                'label_th' => 'แดชบอร์ด',
                'icon' => 'home',
                'route' => '/dashboard',
                'permission' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'id' => 46,
                'parent_id' => null,
                'label' => 'My Approvals',
                'label_en' => 'My Approvals',
                'label_th' => 'รายการรออนุมัติของฉัน',
                'icon' => 'clipboard-document-check',
                'route' => '/approvals/my',
                'permission' => 'approval.approve',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'id' => 48,
                'parent_id' => null,
                'label' => 'Documents',
                'label_en' => 'Documents',
                'label_th' => 'เอกสาร',
                'icon' => 'document',
                'route' => null,
                'permission' => null,
                'sort_order' => 9,
                'is_active' => true,
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'label' => 'Settings',
                'label_en' => 'Settings',
                'label_th' => 'ตั้งค่า',
                'icon' => 'settings',
                'route' => null,
                'permission' => null,
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'id' => 8,
                'parent_id' => 2,
                'label' => 'Organizations',
                'label_en' => 'Organizations',
                'label_th' => 'องค์กร',
                'icon' => 'building-office',
                'route' => '/profile',
                'permission' => 'manage profile',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'id' => 11,
                'parent_id' => 2,
                'label' => 'Departments',
                'label_en' => 'Departments',
                'label_th' => 'ฝ่าย/แผนก',
                'icon' => 'building-office',
                'route' => '/settings/departments',
                'permission' => 'manage_settings',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'id' => 38,
                'parent_id' => 2,
                'label' => 'Positions',
                'label_en' => 'Positions',
                'label_th' => 'ตำแหน่ง',
                'icon' => 'briefcase',
                'route' => '/settings/positions',
                'permission' => 'manage_settings',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'id' => 65,
                'parent_id' => 2,
                'label' => 'Org Chart',
                'label_en' => 'Org Chart',
                'label_th' => 'โครงสร้างองค์กร',
                'icon' => 'building-office',
                'route' => '/settings/org-units',
                'permission' => 'manage_settings',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'id' => 66,
                'parent_id' => 2,
                'label' => 'Substitutions',
                'label_en' => 'Approval Substitutions',
                'label_th' => 'ผู้แทนอนุมัติ',
                'icon' => 'user-group',
                'route' => '/settings/substitutions',
                'permission' => 'manage_settings',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'id' => 73,
                'parent_id' => 2,
                'label' => 'Holidays',
                'label_en' => 'Holiday Calendar',
                'label_th' => 'ปฏิทินวันหยุด',
                'icon' => 'calendar',
                'route' => '/settings/holidays',
                'permission' => 'manage_settings',
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'id' => 74,
                'parent_id' => 2,
                'label' => 'Shifts',
                'label_en' => 'Work Shifts',
                'label_th' => 'ตารางกะทำงาน',
                'icon' => 'clock',
                'route' => '/settings/shifts',
                'permission' => 'manage_settings',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'id' => 3,
                'parent_id' => 2,
                'label' => 'Users',
                'label_en' => 'Users',
                'label_th' => 'ผู้ใช้งาน',
                'icon' => 'users',
                'route' => '/users',
                'permission' => 'user_access.read',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'id' => 4,
                'parent_id' => 2,
                'label' => 'Roles',
                'label_en' => 'Roles',
                'label_th' => 'บทบาท',
                'icon' => 'shield',
                'route' => '/roles',
                'permission' => 'role_access.read',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'id' => 5,
                'parent_id' => 2,
                'label' => 'Permissions',
                'label_en' => 'Permissions',
                'label_th' => 'สิทธิ์การเข้าถึง',
                'icon' => 'key',
                'route' => '/permissions',
                'permission' => 'permission_access.read',
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'id' => 6,
                'parent_id' => 2,
                'label' => 'Password Policy',
                'label_en' => 'Password Policy',
                'label_th' => 'นโยบายรหัสผ่าน',
                'icon' => 'lock-closed',
                'route' => '/settings/password-policy',
                'permission' => 'user_access.update',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'id' => 36,
                'parent_id' => 2,
                'label' => 'Authentication & SSO',
                'label_en' => 'Authentication & SSO',
                'label_th' => 'การยืนยันตัวตนและ SSO',
                'icon' => 'shield-check',
                'route' => '/settings/authentication',
                'permission' => 'manage_settings',
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'id' => 41,
                'parent_id' => 2,
                'label' => 'Document Types',
                'label_en' => 'Document Types',
                'label_th' => 'ประเภทเอกสาร',
                'icon' => 'document-text',
                'route' => '/settings/document-types',
                'permission' => 'manage_settings',
                'sort_order' => 9,
                'is_active' => true,
            ],
            [
                'id' => 33,
                'parent_id' => 2,
                'label' => 'Document Forms',
                'label_en' => 'Document Forms',
                'label_th' => 'ตั้งค่าฟอร์มเอกสาร',
                'icon' => 'document',
                'route' => '/settings/document-forms',
                'permission' => 'manage_settings',
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'id' => 47,
                'parent_id' => 2,
                'label' => 'Lookups',
                'label_en' => 'Lookups',
                'label_th' => 'รายการอ้างอิง',
                'icon' => 'bars-3',
                'route' => '/settings/lookups',
                'permission' => 'manage_settings',
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'id' => 12,
                'parent_id' => 2,
                'label' => 'Workflow',
                'label_en' => 'Workflow',
                'label_th' => 'Workflow',
                'icon' => 'chart-bar',
                'route' => '/settings/workflow',
                'permission' => 'manage_settings',
                'sort_order' => 11,
                'is_active' => true,
            ],
            [
                'id' => 45,
                'parent_id' => 2,
                'label' => 'Running Numbers',
                'label_en' => 'Running Numbers',
                'label_th' => 'เลขที่เอกสารอัตโนมัติ',
                'icon' => 'hashtag',
                'route' => '/settings/running-numbers',
                'permission' => 'manage_settings',
                'sort_order' => 12,
                'is_active' => true,
            ],
            [
                'id' => 34,
                'parent_id' => 2,
                'label' => 'Approval Routing',
                'label_en' => 'Approval routing',
                'label_th' => 'การเลือก workflow อนุมัติ',
                'icon' => 'currency',
                'route' => '/settings/approval-routing',
                'permission' => 'manage_settings',
                'sort_order' => 13,
                'is_active' => true,
            ],
            [
                'id' => 64,
                'parent_id' => 2,
                'label' => 'KPI Cycles',
                'label_en' => 'KPI Cycles',
                'label_th' => 'รอบประเมิน KPI',
                'icon' => 'chart-bar',
                'route' => '/settings/kpi-cycles',
                'permission' => 'manage_settings',
                'sort_order' => 14,
                'is_active' => true,
            ],
            [
                'id' => 37,
                'parent_id' => 2,
                'label' => 'Department workflow bindings',
                'label_en' => 'Dept ↔ workflow',
                'label_th' => 'แผนก ↔ workflow',
                'icon' => 'link',
                'route' => '/settings/department-workflow-bindings',
                'permission' => 'manage_settings',
                'sort_order' => 14,
                'is_active' => false,
            ],
            [
                'id' => 9,
                'parent_id' => 2,
                'label' => 'Branding',
                'label_en' => 'Logo & Background',
                'label_th' => 'โลโก้และพื้นหลัง',
                'icon' => 'document',
                'route' => '/settings/branding',
                'permission' => 'manage_settings',
                'sort_order' => 15,
                'is_active' => true,
            ],
            [
                'id' => 14,
                'parent_id' => 2,
                'label' => 'Notifications',
                'label_en' => 'Notifications',
                'label_th' => 'การแจ้งเตือน',
                'icon' => 'bell',
                'route' => '/settings/notifications',
                'permission' => 'manage_settings',
                'sort_order' => 16,
                'is_active' => true,
            ],
            [
                'id' => 44,
                'parent_id' => 2,
                'label' => 'Branch scoping',
                'label_en' => 'Campus / branch scoping',
                'label_th' => 'สาขา',
                'icon' => 'building-office',
                'route' => '/settings/branch-scoping',
                'permission' => 'manage_settings',
                'sort_order' => 17,
                'is_active' => true,
            ],
            [
                'id' => 7,
                'parent_id' => 2,
                'label' => 'Menu Manager',
                'label_en' => 'Menu Manager',
                'label_th' => 'จัดการเมนู',
                'icon' => 'bars-3',
                'route' => '/settings/navigation',
                'permission' => 'manage_settings',
                'sort_order' => 18,
                'is_active' => true,
            ],
            [
                'id' => 18,
                'parent_id' => 2,
                'label' => 'Activity History',
                'label_en' => 'Activity History',
                'label_th' => 'ประวัติการใช้งาน',
                'icon' => 'clock',
                'route' => '/settings/activity-history',
                'permission' => 'manage_settings',
                'sort_order' => 19,
                'is_active' => true,
            ],
            [
                'id' => 43,
                'parent_id' => 2,
                'label' => 'Dashboards',
                'label_en' => 'Dashboards',
                'label_th' => 'แดชบอร์ด',
                'icon' => 'chart-bar',
                'route' => '/settings/dashboards',
                'permission' => 'manage_settings',
                'sort_order' => 20,
                'is_active' => true,
            ],
            [
                'id' => 53,
                'parent_id' => null,
                'label' => 'My Reports',
                'label_en' => 'My Reports',
                'label_th' => 'รายงานของฉัน',
                'icon' => 'chart-bar',
                'route' => '/my-reports',
                'permission' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'id' => 54,
                'parent_id' => 2,
                'label' => 'Outgoing Webhooks',
                'label_en' => 'Outgoing Webhooks',
                'label_th' => 'Webhook ขาออก',
                'icon' => 'link',
                'route' => '/settings/integrations',
                'permission' => 'manage_settings',
                'sort_order' => 21,
                'is_active' => true,
            ],
            [
                'id' => 61,
                'parent_id' => 2,
                'label' => 'Incoming Webhooks',
                'label_en' => 'Incoming Webhooks',
                'label_th' => 'Webhook ขาเข้า',
                'icon' => 'link',
                'route' => '/settings/inbound-webhooks',
                'permission' => 'manage_settings',
                'sort_order' => 22,
                'is_active' => true,
            ],
            [
                'id' => 62,
                'parent_id' => 2,
                'label' => 'Evaluation Form Settings',
                'label_en' => 'Evaluation Form Settings',
                'label_th' => 'ตั้งค่าฟอร์มประเมิน',
                'icon' => 'star',
                'route' => '/settings/evaluation-form',
                'permission' => 'manage_settings',
                'sort_order' => 23,
                'is_active' => true,
            ],
            [
                'id' => 63,
                'parent_id' => null,
                'label' => 'Evaluation Report',
                'label_en' => 'Evaluation Report',
                'label_th' => 'รายงานประเมิน',
                'icon' => 'chart-bar',
                'route' => '/reports/evaluations',
                'permission' => 'manage_settings',
                'sort_order' => 4,
                'is_active' => true,
            ],
        ];

        foreach ($menus as &$row) {
            $row['created_at'] = $now;
            $row['updated_at'] = $now;
        }
        unset($row);

        NavigationMenu::insert($menus);

        // Re-create form-linked child rows under the Documents (id=48) parent.
        // The wipe above removed any auto-created rows; DocumentForm::saved
        // observer only fires when a form is saved, so backfill explicitly here
        // for every active form (idempotent — syncNavigationMenu upserts).
        \App\Models\DocumentForm::query()
            ->where('is_active', true)
            ->each(fn ($form) => \App\Models\DocumentForm::syncNavigationMenu($form));

        // bulk insert/delete does not fire model events — sidebar cache must refresh
        Cache::forget('navigation_menus_tree');
    }
}
